#ifndef __KERNEL_TYPE_H__
# define __KERNEL_TYPE_H__

typedef enum    xkblas_kernel_type_t
{
    XKBLAS_KERNEL_TYPE_COPYSCALE,
    XKBLAS_KERNEL_TYPE_GEMM,
    XKBLAS_KERNEL_TYPE_GEMMT,
    XKBLAS_KERNEL_TYPE_SYMM,
    XKBLAS_KERNEL_TYPE_SYR2K,
    XKBLAS_KERNEL_TYPE_SYRK,
    XKBLAS_KERNEL_TYPE_TRMM,
    XKBLAS_KERNEL_TYPE_TRSM,
    XKBLAS_KERNEL_TYPE_MAX,

}               xkblas_kernel_type_t;

#endif /* __KERNEL_TYPE_H__ */
