stages:
  - build
  - test

prerequisities-job:
  script:
    - apt-get install cmake

include:
  - local: 'projects/xkrt/.gitlab-ci.yml'
  # - local: 'projects/xkblas/.gitlab-ci.yml'
  # - local: 'projects/xkbm/.gitlab-ci.yml'
