stages:
  - build
  - test

.machine-cpu-only:
    tags:
    - ci.inria.fr
    - large
    - linux
    - v2025

prerequisities-job:
  extends: .machine-cpu-only
  script:
    - apt-get install cmake
  stage: build

include:
  - local: 'projects/xkrt/.gitlab-ci.yml'
  # - local: 'projects/xkblas/.gitlab-ci.yml'
  # - local: 'projects/xkbm/.gitlab-ci.yml'
