# inspired from https://gitlab.inria.fr/gitlabci_gallery/pipelines/complete_cpp_example/-/blob/main/.gitlab-ci.yml?ref_type=heads

stages:
  - build

# defaults for linux docker jobs
default:
  interruptible: true
  tags:
    - ci.inria.fr
    - large
    - linux
    - v2025

# This section runs before each job in the pipeline.
before_script:
  - apt-get update -qq && apt-get install -qqy cmake

include:
  - local: 'projects/xkrt/.gitlab-ci.yml'
  # - local: 'projects/xkblas/.gitlab-ci.yml'
  # - local: 'projects/xkbm/.gitlab-ci.yml'
