#!/bin/bash

##
## Copyright 2009-2013,2018,2019 INRIA
##
## Contributors :
##
## thierry.gautier@inrialpes.fr
##
## This software is a computer program whose purpose is to execute
## blas subroutines on multi-GPUs system.
##
## This software is governed by the CeCILL-C license under French law and
## abiding by the rules of distribution of free software.  You can  use,
## modify and/ or redistribute the software under the terms of the CeCILL-C
## license as circulated by CEA, CNRS and INRIA at the following URL
## "http://www.cecill.info".

## As a counterpart to the access to the source code and  rights to copy,
## modify and redistribute granted by the license, users are provided only
## with a limited warranty  and the software's author,  the holder of the
## economic rights,  and the successive licensors  have only  limited
## liability.

## In this respect, the user's attention is drawn to the risks associated
## with loading,  using,  modifying and/or developing or reproducing the
## software by the user in light of its specific status of free software,
## that may mean  that it is complicated to manipulate,  and  that  also
## therefore means  that it is reserved for developers  and  experienced
## professionals having in-depth computer knowledge. Users are therefore
## encouraged to load and test the software's suitability as regards their
## requirements in conditions enabling the security of their systems and/or
## data to be ensured and,  more generally, to use and operate it in the
## same conditions as regards security.

## The fact that you are presently reading this means that you have had
## knowledge of the CeCILL-C license and that you accept its terms.
##


echo "/* this file is automatically generated */" > internal_register.h
for p in z c d s;
do
  echo "#include \"task_${p}.h\"" >> internal_register.h
done
echo "void xkblas_register_task_format(void) {" >> internal_register.h

# For all kernels generate the format registration function
for t in gemm gemmt trsm trmm syrk syr2k symm herk her2k hemm potrf;
do
  for p in z c d s;
  do
    if [ "$t" = "herk" ] && ([ "$p" != "c" ] && [ "$p" != "z" ]); then
      continue
    fi
    if [ "$t" = "her2k" ] && ([ "$p" != "c" ] && [ "$p" != "z" ]); then
      continue
    fi
    if [ "$t" = "hemm" ] && ([ "$p" != "c" ] && [ "$p" != "z" ]); then
      continue
    fi
    echo "  register_format_$p$t();" >> internal_register.h
  done
done

# avoid using z here : zfiles are source files
for p in c d s;
do
  for f in xkblas_z.h xkblas_f77_z.h task_z.h task_z_internal.h\
           zgemm.c task_zgemm.c \
           zgemmt.c task_zgemmt.c\
           ztrsm.c task_ztrsm.c \
           ztrmm.c task_ztrmm.c\
           zsyrk.c task_zsyrk.c \
           zsyr2k.c task_zsyr2k.c \
           zsymm.c task_zsymm.c \
           zhemm.c task_zhemm.c \
           zherk.c task_zherk.c\
           zher2k.c task_zher2k.c\
           zpotrf.c task_zpotrf.c\
           testing_zauxiliary.c testing_zauxiliary.h\
           testing_zgemm.c\
           testing_ztrsm.c\
           testing_ztrmm.c\
           testing_zsymm.c\
           testing_zsyrk.c\
           testing_zsyr2k.c\
           testing_zhemm.c\
           testing_zherk.c\
           testing_zher2k.c\
           zplgsy.c\
           zplghe.c\
           ;
  do
    if [ ! -e "$f" ]; then
      continue;
    fi
    if [ "$f" = "zhemm.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "task_zhemm.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "zher2k.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "task_zher2k.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "zherk.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "task_zherk.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "zplghe.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "zplghe.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "testing_zhemm.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "testing_zherk.c" ] && [ "$p" != "c" ]; then
      continue
    fi
    if [ "$f" = "testing_zher2k.c" ] && [ "$p" != "c" ]; then
      continue
    fi
echo "generate $f for precision $p"
    if [ "$p" = "z" ]; then
      pm="Z";
      pf="d";
      type=Complex64_t;
      norefvalue=0;
      ctype_format="kaapi_dcplx_format";
      zfloattype="double";
      cutype="cuDoubleComplex";
      ADDR="\&";
    fi
    if [ "$p" = "c" ]; then
      pm="C";
      pf="s";
      type=Complex32_t;
      norefvalue=0;
      ctype_format="kaapi_scplx_format";
      zfloattype="float";
      cutype="cuComplex";
      ADDR="\&";
    fi
    if [ "$p" = "d" ]; then
      pm="D";
      pf="d";
      type=double;
      norefvalue=1;
      ctype_format="kaapi_dbl_format";
      zfloattype="double";
      cutype="double";
      ADDR="";
    fi
    if [ "$p" = "s" ]; then
      pm="S";
      pf="s";
      type=float; 
      norefvalue=1;
      ctype_format="kaapi_flt_format";
      zfloattype="float";
      cutype="float";
      ADDR="";
    fi

    filename=`echo $f | sed -e "s+z+${p}+g"`
    echo $filename


    cat $f |grep -v "#define CBLAS_SADDR" > .tmp
    sed -e "s+Complex64_t+$type+g" \
        -e "s+CFloat64_t+$zfloattype+g" \
        -e "s+NOREFZVALUE+$norefvalue+g" \
        -e "s+task_z+task_${p}+g" \
        -e "s+CBLAS_SADDR\((.*)\)+$ADDR\1+g" \
        -e "s+zauxiliary+${p}auxiliary+g" \
        -e "s+ZGEMM+${p}GEMM+g" \
        -e "s+zgemm+${p}gemm+g" \
        -e "s+Zgemm+${pm}gemm+g" \
        -e "s+ZTRSM+${p}TRSM+g" \
        -e "s+ztrsm+${p}trsm+g" \
        -e "s+Ztrsm+${pm}trsm+g" \
        -e "s+ZTRMM+${p}TRMM+g" \
        -e "s+ztrmm+${p}trmm+g" \
        -e "s+Ztrmm+${pm}trmm+g" \
        -e "s+ZSYRK+${p}SYRK+g" \
        -e "s+zsyrk+${p}syrk+g" \
        -e "s+Zsyrk+${pm}syrk+g" \
        -e "s+ZSYR2K+${p}SYR2K+g" \
        -e "s+zsyr2k+${p}syr2k+g" \
        -e "s+Zsyr2k+${pm}syr2k+g" \
        -e "s+ZSYMM+${p}SYMM+g" \
        -e "s+zsymm+${p}symm+g" \
        -e "s+Zsymm+${pm}symm+g" \
        -e "s+ZHEMM+${p}HEMM+g" \
        -e "s+zhemm+${p}hemm+g" \
        -e "s+Zhemm+${pm}hemm+g" \
        -e "s+ZHERK+${p}HERK+g" \
        -e "s+zherk+${p}herk+g" \
        -e "s+Zherk+${pm}herk+g" \
        -e "s+ZHER2K+${p}HER2K+g" \
        -e "s+zher2k+${p}her2k+g" \
        -e "s+Zher2k+${pm}her2k+g" \
        -e "s+ZPOTRF+${p}POTRF+g" \
        -e "s+zpotrf+${p}potrf+g" \
        -e "s+Zpotrf+${pm}potrf+g" \
        -e "s+cuDoubleComplex+${cutype}+g" \
        -e "s+kaapi_dcplx_format+${ctype_format}+g" .tmp > .tmp2
    mv .tmp2 .tmp
    sed -e "s/zlarn/${p}larn/g" \
        -e "s/zlange/${p}lange/g" \
        -e "s/zaxpy/${p}axpy/g" \
        -e "s/dlamch/${pf}lamch/g" \
        -e "s/dlamch/${pf}lamch/g" \
        -e "s/dhemm/dhemm/g" \
        -e "s/dherk/dsyrk/g" \
        -e "s/dher2k/dsyr2k/g" \
        -e "s/shemm/shemm/g" \
        -e "s/sher2k/ssyr2k/g" \
        -e "s/sherk/ssyrk/g" .tmp > .tmp2
    mv .tmp2 .tmp
    sed -e "s+PRECISION_z+PRECISION_toto+g" .tmp > .tmp2 
    mv .tmp2 .tmp
    sed -e "s+_z+_${p}+g" .tmp \
        -e "s+PRECISION_toto+PRECISION_z+g" > $filename
  done
done

echo "}" >> internal_register.h
