.build_template:
  stage: build
  extends: .machine-cpu-only
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    - make -j
  artifacts:
    paths:
      - build
  needs:
    - job: prerequisities-job
      artifacts: true

build-release:
  extends: .build_template
  variables:
    BUILD_TYPE: "Release"

build-debug:
  extends: .build_template
  variables:
    BUILD_TYPE: "Debug"

