.build_template:
  stage: test-build
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    - make -j
  artifacts:
    paths:
      - build

build-release:
  extends: .build_template
  variables:
    BUILD_TYPE: "Release"

build-debug:
  extends: .build_template
  variables:
    BUILD_TYPE: "Debug"

