/* this file is automatically generated */
#include "task_z.h"
#include "task_c.h"
#include "task_d.h"
#include "task_s.h"
void xkblas_register_task_format(void) {
  register_format_zgemm();
  register_format_cgemm();
  register_format_dgemm();
  register_format_sgemm();
  register_format_zgemmt();
  register_format_cgemmt();
  register_format_dgemmt();
  register_format_sgemmt();
  register_format_ztrsm();
  register_format_ctrsm();
  register_format_dtrsm();
  register_format_strsm();
  register_format_ztrmm();
  register_format_ctrmm();
  register_format_dtrmm();
  register_format_strmm();
  register_format_zsyrk();
  register_format_csyrk();
  register_format_dsyrk();
  register_format_ssyrk();
  register_format_zsyr2k();
  register_format_csyr2k();
  register_format_dsyr2k();
  register_format_ssyr2k();
  register_format_zsymm();
  register_format_csymm();
  register_format_dsymm();
  register_format_ssymm();
  register_format_zherk();
  register_format_cherk();
  register_format_zher2k();
  register_format_cher2k();
  register_format_zhemm();
  register_format_chemm();
  register_format_zpotrf();
  register_format_cpotrf();
  register_format_dpotrf();
  register_format_spotrf();
