#!/bin/bash


# Global variables
PRECISION="z c d s"
BS="128"
N="1024"
NGPU=1
KILLDELAY=10m

#run each kernel
run_GEMM()
{
  p=$1
  n=$2
  b=$3
  echo KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testing_$p 0 1 $b $b GEMM 0.32 0.12 $n $n $n $n $n $n 1
  KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH timeout --signal=KILL $KILLDELAY ./testing_$p 0 1 $b $b GEMM 0.32 0.12 $n $n $n $n $n $n 1
}

run_TRMM()
{
  p=$1
  n=$2
  b=$3
  echo KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testing_$p 0 1 $b $b TRMM 0.3 $n $n $n $n 
  KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH timeout --signal=KILL $KILLDELAY ./testing_$p 0 1 $b $b TRMM 0.3 $n $n $n $n 
}

run_TRSM()
{
  p=$1
  n=$2
  b=$3
  echo KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testing_$p 0 1 $b $b TRSM 0.3 $n $n $n $n 
  KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH timeout --signal=KILL $KILLDELAY ./testing_$p 0 1 $b $b TRSM 0.3 $n $n $n $n 
}

run_SYMM()
{
  p=$1
  n=$2
  b=$3
  echo KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testing_$p 0 1 $b $b SYMM 0.3 0.14 $n $n $n $n $n
  KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH timeout --signal=KILL $KILLDELAY ./testing_$p 0 1 $b $b SYMM 0.3 0.14 $n $n $n $n $n
}

run_SYRK()
{
  p=$1
  n=$2
  b=$3
  echo KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testing_$p 0 1 $b $b SYRK 0.3 0.14 $n $n $n $n
  KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH timeout --signal=KILL $KILLDELAY ./testing_$p 0 1 $b $b SYRK 0.3 0.14 $n $n $n $n
}

run_SYR2K()
{
  p=$1
  n=$2
  b=$3
  echo KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testing_$p 0 1 $b $b SYR2K 0.3 0.14 $n $n $n $n $n
  KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH timeout --signal=KILL $KILLDELAY ./testing_$p 0 1 $b $b SYR2K 0.3 0.14 $n $n $n $n $n
}

run_HEMM()
{
  p=$1
  n=$2
  b=$3
  echo KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testing_$p 0 1 $b $b HEMM 0.3 0.14 $n $n $n $n $n
  KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH timeout --signal=KILL $KILLDELAY ./testing_$p 0 1 $b $b HEMM 0.3 0.14 $n $n $n $n $n
}

run_HERK()
{
  p=$1
  n=$2
  b=$3
  echo KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testing_$p 0 1 $b $b HERK 0.3 0.14 $n $n $n $n
  KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH timeout --signal=KILL $KILLDELAY ./testing_$p 0 1 $b $b HERK 0.3 0.14 $n $n $n $n
}

run_HER2K()
{
  p=$1
  n=$2
  b=$3
  echo KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testing_$p 0 1 $b $b HER2K 0.3 0.14 $n $n $n $n $n
  KAAPI_NUM_GPUS=$NGPU KAAPI_VERBOSE=1 LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH timeout --signal=KILL $KILLDELAY ./testing_$p 0 1 $b $b HER2K 0.3 0.14 $n $n $n $n $n
}





#run test for each precision
LISTKERN_Z="GEMM TRMM TRSM SYMM SYRK SYR2K HEMM HERK HER2K"
LISTKERN_D="GEMM TRMM TRSM SYMM SYRK SYR2K"

#
runtest_z()
{
  for kern in $LISTKERN_Z;
  do
    echo run_$kern z $1 $2
    run_$kern z $1 $2
  done
}

#
runtest_c()
{
  for kern in $LISTKERN_Z;
  do
    echo run_$kern c $1 $2
    run_$kern c $1 $2
  done
}

#
runtest_d()
{
  for kern in $LISTKERN_D;
  do
    echo run_$kern d $1 $2
    run_$kern d $1 $2
  done
}

#
runtest_s()
{
  for kern in $LISTKERN_D;
  do
    echo run_$kern s $1 $2
    run_$kern s $1 $2
  done
}



#
dotest()
{
  for p in $PRECISION; 
  do
    echo "----- PRECISION: $p   - NGPU: $NGPU"
    for n in $N;
    do
      for b in $BS;
      do
        echo runtest_$p $n $b
        runtest_$p $n $b |tee -a log|grep TESTING
      done
    done
  done
}


GPUCOUNT=`nvidia-smi --query-gpu=gpu_name --format=csv| grep -v name | wc -l`
GSET=`seq -s ' ' $GPUCOUNT -1 1`

for NGPU in $GSET;
do

  N=1024
  BS=128
  KILLDELAY=5m
  echo "--- Run test with N="$N", BS="$BS
  dotest;

  N=2048
  BS=512
  KILLDELAY=20m
  echo "--- Run test with N="$N", BS="$BS
  dotest;

  N=8192
  BS=1024
  KILLDELAY=35m
  echo "--- Run test with N="$N", BS="$BS
  dotest;

done

